---
  - name: download passenger release file
    get_url: dest=/etc/yum.repos.d/passenger.repo url=https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo

  - name: get passenger gpg key
    get_url: dest=/etc/pki/rpm-gpg/passenger.key url=https://packagecloud.io/gpg.key

  - name: install epel repo
    action: yum pkg={{item}} state=present
    with_items:
      - epel-release

  - name: required packages
    action: yum pkg={{item}} state=present
    with_items:
      - etckeeper
      - git
      - libxml2-devel
      - ImageMagick-devel
      - MySQL-python
      - httpd
      - mysql-devel
      - mysql
      - mariadb-server
      - ruby-devel
      - system-config-firewall-base
      - "@development-tools"

  - name: disable firewall
    service: name=firewalld state=stopped

  - name: disable selinux
    command: setenforce 0

  - name: ensure services are enabled and started
    service: name={{item}} state=started enabled=yes
    with_items:
      - httpd
      - mariadb

###
### setup mysql for redmine
###
  - name: create db
    mysql_db: db={{redmine_db}} state=present
    notify:
      - restart mariadb

  - name: create user for redmine db
    mysql_user: state=present name={{redmine_dbuser}} password={{redmine_dbpass}} priv={{redmine_db}}.*:ALL
    notify:
      - restart mariadb

###
### download and install passenger
###
  - name: install mod passenger
    yum: name=mod_passenger state=present
    notify:
      - restart httpd

###
### download and install redmine
###
  - name: clone redmine stable repo
    git: repo=https://github.com/redmine/redmine.git dest=/var/www/redmine version=2.3-stable

  - name: install redmine database.yml
    template: src=/home/daniel/workspace/ansible-redmine/templates/database.yml dest=/var/www/redmine/config/database.yml

  - name: install bundler
    command: gem install bundler creates=/usr/bin/bundle

  - name: install dependencies for redmine
    command: bundle install --without development test chdir=/var/www/redmine

  - name: install redmine httpd conf
    template: src=/home/daniel/workspace/ansible-redmine/templates/redmine.conf dest=/etc/httpd/conf.d/redmine.conf
    notify:
      - restart httpd

  - name: generate secret token
    command: rake generate_secret_token chdir=/var/www/redmine

  - name: initialise db for redmine
    command: rake db:migrate RAILS_ENV=production chdir=/var/www/redmine

  - name: create some temp/cache directories | ideally some of the redmine setups should be setup as apache user
    file: path={{item}} state=directory
    with_items:
      - /var/www/redmine/tmp/cache

  - name: chown the redmine directory apache user and group
    file: path=/var/www/redmine state=directory owner=apache group=apache recurse=yes

  - name: load default data into redmine
    command: rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG={{redmine_lang}} chdir=/var/www/redmine
    notify:
      - restart httpd
